<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/adimchi/image/upload/v1554498665/adimchi_pic_1.png" alt="Iwuanyanwu Adimchinobi">
                        <h6>IWUANYANWU ADIMCHINOBI</h6>
                        <p>Front-end Engineer</p>
                        <ul class="list">
                           <li><a href="#" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="#" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="#" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p>A young promising web developer who has passion for ict and willing to learn new ways to acheive set goals i have little idea on php and java script but ready to collaborate with experts to learn that which i dont know   </p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | PHP | HTML</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
